--- #YAML:1.0
name:                File-Find-Closures
version:             1.08
abstract:            functions you can use with File::Find
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Find:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
