# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Find-Closures
version:      0.10_03
version_from: lib/Closures.pm
installdirs:  site
requires:
    File::Find:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
