---
abstract: 'functions you can use with File::Find'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Find-Closures
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/briandfoy/file-find-closures
version: 1.10
